### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by huzhihong** [KarolS/hOCR4J#1]
How to use?

**Comment by KarolS** [comment]
1. Load your HOCR files into strings in whatever way.
2. Call `Page.fromHocr`:

        List<String> hocr = ...
        List<Page> pages = Page.fromHocr(hocr);

You now have a list of page elements. For the most basic usage, you might want to iterate over all words in the document:

    for (Page page: pages)
    for (Area area: page)
    for (Paragraph para: area)
    for (Line line: para)
    for (Word word: line) {
        String text = word.getText();
        ...
    }

Or you can use available methods to search for lines with certain properties, for example if you're trying to parse table-like layouts, or are looking for a total near the word "Total", and so on.

What are you planning to achieve?

**Comment by huzhihong** [comment]
String hocr = FileUtil.readFile(new File("E:\\OCR_HOME\\pdf_result\\bcd49814-908c-4a75-8147-ebb44c892d65.hocr"), "utf-8");
 List<Page> list =  HocrParser.parse(hocr);

I tried it，but program error：java.lang.NullPointerException
	at io.github.karols.hocr4j.dom.HocrParser.parse(HocrParser.java:106)
	at io.github.karols.hocr4j.dom.HocrParser.parse(HocrParser.java:100)
	at io.github.karols.hocr4j.dom.HocrParser.parse(HocrParser.java:118)
	at io.github.karols.hocr4j.dom.HocrParserTest.testParseHocr(HocrParserTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

 I want to parse Hocr file that Tesseract OCR return

**Comment by KarolS** [comment]
It probably means that the format of the file isn't what the library is expecting. The HOCR files should contain a `<body>` tag and the library doesn't handle the case when it's missing.

It might be also the case that current Tesseract versions are no longer compatible. For the record, last time I used this library was 4 years ago with Tesseract 3.02.

Do you have a small sample HOCR file you can publicly post?

**Comment by huzhihong** [comment]
[ed2bc628-07d4-47c8-ad77-8e2ca5c1a595.txt](https://github.com/KarolS/hOCR4J/files/2255696/ed2bc628-07d4-47c8-ad77-8e2ca5c1a595.txt)

**Comment by huzhihong** [comment]
Thanks! I do this with Tesseract  4.0.0-beta.3.
